baseURL = "https://dev.kem.li"
languageCode = "en-gb"
title = "dev"
copyright = "Andrew Kember"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-0RZR8M66RS"
enableRobotsTXT = true
theme = "ananke"

[markup.goldmark.renderer]
unsafe= true

# Publish stuff?
# publishDir = "docs"

# [module]
#   [[module.imports]]
#     # Theme
#     path = "github.com/theNewDynamic/gohugo-theme-ananke"

#   [[module.imports.mounts]]
#       source = "layouts/partials"
#       target = "layouts/partials"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/static/images-header/ak-logo-2021.svg"
  site_logo = "/static/images-header/ak-logo-2021-white.svg"
  description = "Because blogs are dead"
  twitter = "https://twitter.com/andrewkember"
  github = "https://github.com/andrewkember"
  linkedin = "https://www.linkedin.com/in/andrewkember/"
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = "/static/images-header/kemli-sunset-1.jpg"
  #featured_image = ""
  recent_posts_number = 2