baseURL = "https://dev.kem.li"
languageCode = "en-gb"
title = "dev"
copyright = "Andrew Kember"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30 # this is set low for demonstrating with dummy content. Set to a higher number
#googleAnalytics = ""
enableRobotsTXT = true

# Publish stuff?
# publishDir = "docs"

[module]
  [[module.imports]]
    # Theme
    path = "github.com/theNewDynamic/gohugo-theme-ananke"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Because blogs are dead"
  twitter = "https://twitter.com/andrewkember"
  github = "https://github.com/andrewkember"
  linkedin = "https://www.linkedin.com/in/andrewkember/"
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = "/images-header/kemli-sunset-1.jpg"
  recent_posts_number = 2